### ISSUE TITLE
Problem to create a new ticket wirh russian letters

### ISSUE THREAD

**Issue by glowsub** [truly-systems/glpi-sdk-python#22]
Hi guys, I have a little problem here. When I try to create a new ticket using russian letters in 'name' and 'content' parametres, there is an exception occuring. My script:

```
from glpi import GLPI
import json

url = 'https://hd.integrasky.ru/apirest.php'
user = 'username'
password = 'password'
glpi_token = 'token'
glpi = GLPI(url, glpi_token, (user, password))
ticket_payload = {'name': 'Проблема', 'content': 'Не включается компьютер', 'entities_id': 29}
ticket_dict = glpi.create('ticket', ticket_payload)
success_message = (json.dumps(ticket_dict, indent=2, separators=(',', ': '), sort_keys=True, ensure_ascii=False))
if isinstance(ticket_dict, dict):
    print(success_message)
```
And exception:
```

Traceback (most recent call last):
  File "C:\Users\makarenko\PycharmProjects\glpi_bot\venv\lib\site-packages\glpi\glpi.py", line 221, in set_session_token
    err = _glpi_html_parser(r.content)
  File "C:\Users\makarenko\PycharmProjects\glpi_bot\venv\lib\site-packages\glpi\glpi.py", line 100, in _glpi_html_parser
    html_parser = GlpiHTMLParser(content)
  File "C:\Users\makarenko\PycharmProjects\glpi_bot\venv\lib\site-packages\glpi\glpi.py", line 76, in __init__
    self.feed(content)
  File "C:\Users\makarenko\AppData\Local\Programs\Python\Python36-32\lib\html\parser.py", line 110, in feed
    self.rawdata = self.rawdata + data
TypeError: must be str, not bytes

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/makarenko/PycharmProjects/glpi_bot/glpi_only.py", line 15, in <module>
    ticket_dict = glpi.create('ticket', ticket_payload)
  File "C:\Users\makarenko\PycharmProjects\glpi_bot\venv\lib\site-packages\glpi\glpi.py", line 504, in create
    self.init_api()
  File "C:\Users\makarenko\PycharmProjects\glpi_bot\venv\lib\site-packages\glpi\glpi.py", line 481, in init_api
    self.api_session = self.api_rest.get_session_token()
  File "C:\Users\makarenko\PycharmProjects\glpi_bot\venv\lib\site-packages\glpi\glpi.py", line 236, in get_session_token
    self.set_session_token()
  File "C:\Users\makarenko\PycharmProjects\glpi_bot\venv\lib\site-packages\glpi\glpi.py", line 224, in set_session_token
    err = _glpi_html_parser(r.content)
  File "C:\Users\makarenko\PycharmProjects\glpi_bot\venv\lib\site-packages\glpi\glpi.py", line 100, in _glpi_html_parser
    html_parser = GlpiHTMLParser(content)
  File "C:\Users\makarenko\PycharmProjects\glpi_bot\venv\lib\site-packages\glpi\glpi.py", line 76, in __init__
    self.feed(content)
  File "C:\Users\makarenko\AppData\Local\Programs\Python\Python36-32\lib\html\parser.py", line 110, in feed
    self.rawdata = self.rawdata + data
TypeError: must be str, not bytes

Process finished with exit code 1
```

**Comment by augustoferronato** [comment]
We are looking at this issue

**Comment by glowsub** [comment]
I found a solution. We need use   .encode('utf-8').decode('latin-1')
Example:
ticket_payload = {
            'name': 'Проблема с компьютером'.encode('utf-8').decode('latin-1')
            'content': 'Компьютер не включается'.encode('utf-8').decode('latin-1')
}

**Comment by glowsub** [comment]
I closed that issue, and add solution there.
Now I have a new question. How can I change a 'Requestor' name, when I'm
creating a ticket?
[image: Сохраненное изображение 2018-8-5_22-11-13.719.jpg]

пн, 30 июл. 2018 г. в 21:58, Augusto Ferronato <notifications@github.com>:
