### ISSUE TITLE
Error:  "user_token "+self.token_auth TypeError: can only concatenate str (not "tuple") to str

### ISSUE THREAD

**Issue by wtccosta** [truly-systems/glpi-sdk-python#32]
When I try to run the installation guide examples, such as listing tickets, this error appears: 
 "user_token "+self.token_auth
Traceback (most recent call last):
  File "C:/Users/warde/PycharmProjects/pyGLPI/connection.py", line 13, in <module>
    glpi.get_all('ticket')
  File "c:\users\warde\pycharmprojects\pyglpi\venv\src\glpi\glpi\glpi.py", line 589, in get_all
    self.init_api()
  File "c:\users\warde\pycharmprojects\pyglpi\venv\src\glpi\glpi\glpi.py", line 544, in init_api
    self.api_session = self.api_rest.get_session_token()
  File "c:\users\warde\pycharmprojects\pyglpi\venv\src\glpi\glpi\glpi.py", line 271, in get_session_token
    self.set_session_token()
  File "c:\users\warde\pycharmprojects\pyglpi\venv\src\glpi\glpi\glpi.py", line 211, in set_session_token
    headers["Authorization"] = "user_token "+self.token_auth
TypeError: can only concatenate str (not "tuple") to str

I use python version 3.7

**Comment by Eleazarus** [comment]
Hello,

Same error on Python 2.7.5, with the last version 0.4.0 (GLPI 9.4.3). Is this still maintained?

**Comment by jsalatiel** [comment]
Same problem here with python 2.7.15  with the last version 0.4.0 .

**Comment by KongNan** [comment]
3.7, same error.

**Comment by polkaa** [comment]
Mistake is in the utiliszation of GLPI constructor :
```python
glpi = GLPI(url, token, (user, password))
```
(README)
while the constructor has the following signature :
```python
def __init__(self, url, app_token, auth_token,
                 item_map=None):
```
(glpi/glpi.py)

GLPI constructor does not take a tuple of user and password as argument but an authentification token.

**Comment by manubuhay** [comment]
> Mistake is in the utiliszation of GLPI constructor :
> 
> ```python
> glpi = GLPI(url, token, (user, password))
> ```
> 
> (README) while the constructor has the following signature :
> 
> ```python
> def __init__(self, url, app_token, auth_token,
>                  item_map=None):
> ```
> 
> (glpi/glpi.py)
> 
> GLPI constructor does not take a tuple of user and password as argument but an authentification token.

Thank you, all the while I thought my code was the issue.
